<a href="https://colab.research.google.com/github/xhxuciedu/cs273p/blob/main/stanford_cs337.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# prompt: import torch numpy

import torch
import numpy as np
import torch.nn as nn

In [6]:
x = torch.tensor([[1., 2, 3], [4, 5, 6]])  # inspect x
x = torch.zeros(4, 8)  # 4x8 matrix of all zeros @inspect x
x = torch.ones(4, 8)  # 4x8 matrix of all ones @inspect x
x = torch.randn(4, 8)  # 4x8 matrix of iid Normal(0, 1) samples @inspect x

In [5]:
x.shape

torch.Size([4, 8])

In [7]:
x = torch.empty(4, 8)  # 4x8 matrix of uninitialized values @inspect x

In [11]:
nn.init.trunc_normal_(x, mean=0, std=1, a=-2, b=2)  # inspect x

tensor([[-0.6606, -0.8385,  1.9048,  0.9402,  0.7740, -0.1420,  0.2943, -0.9464],
        [-0.6215, -0.2329, -0.4170, -1.3607,  0.0105,  0.5321,  0.7235,  0.0807],
        [-0.1346,  0.8960, -0.5308, -1.6812,  0.6533, -1.2736,  0.9348,  0.0752],
        [-1.0630,  0.3205,  0.1983,  0.0081, -1.1420, -0.3746,  0.6032,  0.3492]])

In [13]:
import torch
import numpy as np
import torch.nn as nn

def get_memory_usage(tensor):
  """Calculates the memory usage of a PyTorch tensor in bytes.

  Args:
    tensor: The PyTorch tensor.

  Returns:
    The memory usage of the tensor in bytes.
  """
  return tensor.element_size() * tensor.nelement()

x = torch.tensor([[1., 2, 3], [4, 5, 6]])  # inspect x
x = torch.zeros(4, 8)  # 4x8 matrix of all zeros @inspect x
x = torch.ones(4, 8)  # 4x8 matrix of all ones @inspect x
x = torch.randn(4, 8)  # 4x8 matrix of iid Normal(0, 1) samples @inspect x
x.shape
x = torch.empty(4, 8)  # 4x8 matrix of uninitialized values @inspect x
nn.init.trunc_normal_(x, mean=0, std=1, a=-2, b=2)  # inspect x
x = torch.zeros(4, 8)  # @markdown x
assert x.dtype == torch.float32  # Default type
assert x.numel() == 4 * 8
assert x.element_size() == 4  # Float is 4 bytes


In [14]:
assert get_memory_usage(x) == 4 * 8 * 4  # 128 bytes
#One matrix in the feedforward layer of GPT-3:
assert get_memory_usage(torch.empty(12288 * 4, 12288)) == 2304 * 1024 * 1024  # 2.3 GB
#...which is a lot!

In [15]:
#However, the dynamic range (especially for small numbers) isn't great.
x = torch.tensor([1e-8], dtype=torch.float16)  # @inspect x
assert x == 0  # Underflow!

tensor([0.], dtype=torch.float16)

In [17]:
#Let's compare the dynamic ranges and memory usage of the different data types:
float32_info = torch.finfo(torch.float32)  # @inspect float32_info
float16_info = torch.finfo(torch.float16)  # @inspect float16_info
bfloat16_info = torch.finfo(torch.bfloat16)  # @inspect bfloat16_info

In [18]:
float32_info

finfo(resolution=1e-06, min=-3.40282e+38, max=3.40282e+38, eps=1.19209e-07, smallest_normal=1.17549e-38, tiny=1.17549e-38, dtype=float32)

In [19]:
float16_info

finfo(resolution=0.001, min=-65504, max=65504, eps=0.000976562, smallest_normal=6.10352e-05, tiny=6.10352e-05, dtype=float16)

In [20]:
bfloat16_info

finfo(resolution=0.01, min=-3.38953e+38, max=3.38953e+38, eps=0.0078125, smallest_normal=1.17549e-38, tiny=1.17549e-38, dtype=bfloat16)

In [7]:
# prompt:     Let's first see if we have any GPUs.
#     if not torch.cuda.is_available():
#         return
#     num_gpus = torch.cuda.device_count()  # @inspect num_gpus
#     for i in range(num_gpus):
#         properties = torch.cuda.get_device_properties(i)  # @inspect properties
#     memory_allocated = torch.cuda.memory_allocated()  # @inspect memory_allocated
#     text("Move the tensor to GPU memory (device 0).")
#     y = x.to("cuda:0")
#     assert y.device == torch.device("cuda", 0)
#     text("Or create a tensor directly on the GPU:")
#     z = torch.zeros(32, 32, device="cuda:0")
#     new_memory_allocated = torch.cuda.memory_allocated()  # @inspect new_memory_allocated
#     memory_used = new_memory_allocated - memory_allocated  # @inspect memory_used
#     assert memory_used == 2 * (32 * 32 * 4)  # 2 32x32 matrices of 4-byte floats
# generate code. comments

import torch
import torch.nn as nn

# Check for GPU availability
if not torch.cuda.is_available():
    print("CUDA is not available.")
else:
    num_gpus = torch.cuda.device_count()
    print(f"Number of GPUs available: {num_gpus}")

    for i in range(num_gpus):
        properties = torch.cuda.get_device_properties(i)
        print(f"GPU {i} properties: {properties}")

    # Example tensor operations on GPU
    x = torch.randn(32, 32)  # Example tensor

    memory_allocated = torch.cuda.memory_allocated()
    print(f"Initial GPU memory allocated: {memory_allocated}")

    # Move tensor to GPU
    y = x.to("cuda:0")
    print(f"Tensor 'y' device: {y.device}")

    # Create tensor directly on GPU
    z = torch.zeros(32, 32, device="cuda:0")

    new_memory_allocated = torch.cuda.memory_allocated()
    print(f"New GPU memory allocated: {new_memory_allocated}")

    memory_used = new_memory_allocated - memory_allocated
    print(f"Memory used by 'z': {memory_used}")
    assert memory_used == 2 * (32 * 32 * 4), "Memory usage mismatch"


Number of GPUs available: 1
GPU 0 properties: _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15095MB, multi_processor_count=40, uuid=8116d4dc-edda-5eef-5119-21095b8e6791, L2_cache_size=4MB)
Initial GPU memory allocated: 8192
Tensor 'y' device: cuda:0
New GPU memory allocated: 16384
Memory used by 'z': 8192


In [8]:
x.shape

torch.Size([32, 32])

In [6]:
x.stride()

(32, 1)

In [9]:
#Note that some views are non-contiguous entries, which means that further views aren't possible.
x = torch.tensor([[1., 2, 3], [4, 5, 6]])  # inspect x
y = x.transpose(1, 0)  # @inspect y
assert not y.is_contiguous()

In [10]:
x.shape

torch.Size([2, 3])

In [11]:
y.shape

torch.Size([3, 2])

In [15]:
y.is_contiguous()

False

In [18]:
y.reshape(2,3)

tensor([[1., 4., 2.],
        [5., 3., 6.]])

In [20]:
y

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [21]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [22]:
x.reshape(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [23]:
z = y.reshape(2,3)

In [24]:
z

tensor([[1., 4., 2.],
        [5., 3., 6.]])

In [25]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
 z.is_contiguous()

True

In [28]:
import torch

def same_storage(tensor1, tensor2):
  """Checks if two PyTorch tensors share the same underlying storage.

  Args:
    tensor1: The first PyTorch tensor.
    tensor2: The second PyTorch tensor.

  Returns:
    True if the tensors share the same storage, False otherwise.
  """
  return tensor1.storage().data_ptr() == tensor2.storage().data_ptr()

In [29]:
#One can enforce a tensor to be contiguous first:
y = x.transpose(1, 0).contiguous().view(2, 3)  # inspect y
assert not same_storage(x, y)

<ipython-input-28-670effeede1e>:13: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return tensor1.storage().data_ptr() == tensor2.storage().data_ptr()


In [30]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [31]:
y

tensor([[1., 4., 2.],
        [5., 3., 6.]])

In [1]:
!pip install jaxtyping

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 3.7 MB/s eta 0:00:00


In [2]:
from jaxtyping import Float
import torch

#Old way:
x = torch.ones(2, 2, 1, 3)  # batch seq heads hidden  @inspect x
#    New (jaxtyping) way:
x: Float[torch.Tensor, "batch seq heads hidden"] = torch.ones(2, 2, 1, 3)

In [3]:
x.shape

torch.Size([2, 2, 1, 3])

In [4]:
# prompt:    Define two tensors:
#     x: Float[torch.Tensor, "batch seq1 hidden"] = torch.ones(2, 3, 4)  # @inspect x
#     y: Float[torch.Tensor, "batch seq2 hidden"] = torch.ones(2, 3, 4)  # @inspect y
#     Old way:
#     z = x @ y.transpose(-2, -1)  # batch, sequence, sequence  @inspect z
#     New (einops) way:
#     z = einsum(x, y, "batch seq1 hidden, batch seq2 hidden -> batch seq1 seq2")  # @inspect z
#     Dimensions that are not named in the output are summed over.
#     Or can use ... to represent broadcasting over any number of dimensions:
#     z = einsum(x, y, "... seq1 hidden, ... seq2 hidden -> ... seq1 seq2")  # @inspect z
# generate code

from jaxtyping import Float
import torch

#Old way:
x = torch.ones(2, 2, 1, 3)  # batch seq heads hidden  @inspect x
y = torch.ones(2, 2, 1, 3) # batch seq heads hidden

z = torch.einsum("bshd,bshd->bsh", x, y)

#New (jaxtyping) way:
x: Float[torch.Tensor, "batch seq heads hidden"] = torch.ones(2, 2, 1, 3)
y: Float[torch.Tensor, "batch seq heads hidden"] = torch.ones(2, 2, 1, 3)



RuntimeError: einsum(): the number of subscripts in the equation (19) does not match the number of dimensions (4) for operand 0 and no ellipsis was given

In [7]:
!pip install einops



In [14]:
from einops import einsum, rearrange, reduce

In [10]:
# prompt: z = torch.einsum("batch seq heads hidden,batch seq heads hidden->batch seq heads", x, y)
# z
# rewrite it in correct format

z = einsum(x, y, "batch seq heads hidden, batch seq heads hidden -> batch seq heads")


In [11]:
z.shape

torch.Size([2, 2, 1])

In [15]:
x: Float[torch.Tensor, "batch seq hidden"] = torch.ones(2, 3, 4)  # inspect x
#Old way:
y = x.mean(dim=-1)  # inspect y
#New (einops) way:
y = reduce(x, "... hidden -> ...", "sum")  # inspect y

In [16]:
x.shape,  y.shape

(torch.Size([2, 3, 4]), torch.Size([2, 3]))

In [17]:
# prompt:     Sometimes, a dimension represents two dimensions
#     ...and you want to operate on one of them.
#     x: Float[torch.Tensor, "batch seq total_hidden"] = torch.ones(2, 3, 8)  # @inspect x
#     ...where total_hidden is a flattened representation of heads * hidden1
#     w: Float[torch.Tensor, "hidden1 hidden2"] = torch.ones(4, 4)
#     Break up total_hidden into two dimensions (heads and hidden1):
#     x = rearrange(x, "... (heads hidden1) -> ... heads hidden1", heads=2)  # @inspect x
#     Perform the transformation by w:
#     x = einsum(x, w, "... hidden1, hidden1 hidden2 -> ... hidden2")  # @inspect x
#     Combine heads and hidden2 back together:
#     x = rearrange(x, "... heads hidden2 -> ... (heads hidden2)")  # @inspect x
# convert the above to code

from einops import einsum, rearrange

x: Float[torch.Tensor, "batch seq total_hidden"] = torch.ones(2, 3, 8)
w: Float[torch.Tensor, "hidden1 hidden2"] = torch.ones(4, 4)

x1 = rearrange(x, "... (heads hidden1) -> ... heads hidden1", heads=2)
x2 = einsum(x1, w, "... hidden1, hidden1 hidden2 -> ... hidden2")
x3 = rearrange(x2, "... heads hidden2 -> ... (heads hidden2)")


In [18]:
x.shape

torch.Size([2, 3, 8])

In [19]:
x1.shape

torch.Size([2, 3, 2, 4])

In [20]:
x2.shape

torch.Size([2, 3, 2, 4])

In [21]:
# prompt: Intuitions
#     Training GPT-3 (2020) took 3.14e23 FLOPs.  [article]
#     Training GPT-4 (2023) is speculated to take 2e25 FLOPs  [article]
#     US executive order: any foundation model trained with >= 1e26 FLOPs must be reported to the government (revoked in 2025)
#     A100 has a peak performance of 312 teraFLOP/s  [spec]
#     assert a100_flop_per_sec == 312e12
#     H100 has a peak performance of 1979 teraFLOP/s with sparsity, 50% without  [spec]
#     assert h100_flop_per_sec == 1979e12 / 2
#     8 H100s for 2 weeks:
#     total_flops = 8 * (60 * 60 * 24 * 7) * h100_flop_per_sec  # @inspect total_flops
# convert the above to code

# import torch
# import numpy as np
# import torch.nn as nn
# from jaxtyping import Float
# from einops import einsum, rearrange, reduce

# Constants
a100_flop_per_sec = 312e12
h100_flop_per_sec = 1979e12 / 2

# Calculate total FLOPs for 8 H100s over 2 weeks
total_flops = 8 * (60 * 60 * 24 * 14) * h100_flop_per_sec
print(f"Total FLOPs for 8 H100s over 2 weeks: {total_flops}")


Total FLOPs for 8 H100s over 2 weeks: 9.5751936e+21


In [23]:
# prompt: device = get_device()
# implement get_device function

import torch

def get_device():
  """
  Gets the appropriate device (GPU if available, otherwise CPU).
  """
  if torch.cuda.is_available():
    return torch.device("cuda:0")  # Use the first available GPU
  else:
    return torch.device("cpu")


In [24]:
if torch.cuda.is_available():
    B = 16384  # Number of points
    D = 32768  # Dimension
    K = 8192   # Number of outputs
else:
    B = 1024
    D = 256
    K = 64
device = get_device()
x = torch.ones(B, D, device=device)
w = torch.randn(D, K, device=device)
y = x @ w

In [25]:
# We have one multiplication (x[i][j] * w[j][k]) and one addition per (i, j, k) triple.
actual_num_flops = 2 * B * D * K  # inspect actual_num_flops

In [26]:
actual_num_flops

8796093022208

In [27]:
# prompt: show actual_num_flops in scientific notation

print(f"{actual_num_flops:.2e}")


8.80e+12


In [28]:
device

device(type='cuda', index=0)